application: computerjeff
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

# builtins:
# - appstats: on
# - admin_redirect: on
# - deferred: on
# - remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

skip_files:
- ^(node_modules)
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# inbound_services:
# - warmup

handlers:
- url: /computer_icon.ico
  static_files: jeff/static/images/computer_icon.ico
  upload: jeff/static/images/computer_icon.ico

# - url: /*.svg
#   static_files: menu/static/image/*.svg
#   upload: menu/static/image/*.svg
#   mime_type: image/svg+xml
  # http_headers:
    # Content-Type: 'image/svg+xml'

# - url: /robots.txt
#   static_files: menu/static/robots.txt
#   upload: menu/static/robots.txt

# - url: /gae_mini_profiler/static
#   static_dir: lib/gae_mini_profiler/static

# - url: /gae_mini_profiler/.*
#   script: lib.gae_mini_profiler.main.menu

- url: /sitemap.xml    
  static_files: jeff/static/sitemap.xml
  upload: jeff/static/sitemap.xml

- url: /static
  static_dir: jeff/static

- url: .*
  script: jeff.app