application: computerjeff
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "60d"

# builtins:
# - appstats: on
# - admin_redirect: on
# - deferred: on
# - remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

skip_files:
- ^(node_modules)
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# inbound_services:
# - warmup

handlers:
- url: /computer_icon.ico
  static_files: jeff/static/images/computer_icon.ico
  upload: jeff/static/images/computer_icon.ico

# - url: /(.*\.(gif|png|jpg))$
#   static_files: static/images/images_build/\1
#   upload: static/images/images_build/.*\.(gif|png|jpg)$

- url: /*.svg
  static_files: jeff/static/images/images_build/*.svg
  upload: jeff/static/images/images_build/*.svg
  mime_type: image/svg+xml
  # http_headers:
    # Content-Type: 'image/svg+xml'

- url: /*.webp
  static_files: jeff/static/images/images_build/*.webp
  upload: jeff/static/images/images_build/*.webp
  mime_type: image/webp

# - url: /robots.txt
#   static_files: menu/static/robots.txt
#   upload: menu/static/robots.txt

# - url: /gae_mini_profiler/static
#   static_dir: lib/gae_mini_profiler/static

# - url: /gae_mini_profiler/.*
#   script: lib.gae_mini_profiler.main.menu

- url: /(robots\.txt|humans\.txt|crossdomain\.xml|sitemap\.xml)
  static_files: jeff/static/\1
  upload: jeff/static/(robots\.txt|humans\.txt|crossdomain\.xml|sitemap\.xml)

- url: /static
  static_dir: jeff/static

- url: .*
  script: jeff.app